apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-docker-app
  labels:
    app: ruby-docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ruby-docker-app
  template:
    metadata:
      labels:
        app: ruby-docker-app
    spec:
      containers:
      - name: ruby-docker-app
        image: 150139297236.dkr.ecr.us-east-1.amazonaws.com/ruby-docker-app:REPLACE_GIT_SHA
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: production-env-file
        env:
        - name: NODE_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
