apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-docker-app-deployment
  labels:
    app: ruby-docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ruby-docker-app
  template:
    metadata:
      labels:
        app: ruby-docker-app
    spec:
      containers:
      - name: ruby-docker-app
        image: 219445987607.dkr.ecr.us-east-1.amazonaws.com/ruby-docker-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: RUBY_DOCKER_APP_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: production-env-file
              key: RUBY_DOCKER_APP_DATABASE_HOST
        - name: RUBY_DOCKER_APP_DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: production-env-file
              key: RUBY_DOCKER_APP_DATABASE_USERNAME
        - name: RUBY_DOCKER_APP_DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: production-env-file
              key: RUBY_DOCKER_APP_DATABASE_PASSWORD
