apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-docker-app
  labels:
    app: ruby-docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ruby-docker-app
  template:
    metadata:
      labels:
        app: ruby-docker-app
    spec:
      containers:
      - name: ruby-docker-app
        image: 452783090577.dkr.ecr.us-east-1.amazonaws.com/ruby-docker-app:REPLACE_GIT_SHA
        ports:
        - containerPort: 3000
        env:
        - name: RUBY_DOCKER_APP_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: production-env-file
              key: RUBY_DOCKER_APP_DATABASE_HOST
        - name: RUBY_DOCKER_APP_DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: production-env-file
              key: RUBY_DOCKER_APP_DATABASE_USERNAME
        - name: RUBY_DOCKER_APP_DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: production-env-file
              key: RUBY_DOCKER_APP_DATABASE_PASSWORD
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              name: production-env-file
              key: RAILS_ENV
        - name: MEMCACHED_SERVER
          valueFrom:
            configMapKeyRef:
              name: production-env-file
              key: MEMCACHED_SERVER
        - name: CLOUDFRONT_DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              name: production-env-file
              key: CLOUDFRONT_DOMAIN_NAME
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: production-env-file
              key: S3_BUCKET
        - name: RAILS_SERVE_STATIC_FILES
          valueFrom:
            configMapKeyRef:
              name: production-env-file
              key: RAILS_SERVE_STATIC_FILES
        - name: NODE_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
