version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
    - /tmp/ruby-docker-app/db:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=password

  redis:
    image: redis
    container_name: redis

  memcached:
    build:
      context: .
      dockerfile: ./docker/memcached/Dockerfile
    image: my-memcached
    container_name: memcached
    ports:
    - 11211:11211

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: 163963319917.dkr.ecr.us-east-1.amazonaws.com/ruby-docker-app:latest
    working_dir: /app
    container_name: web
    restart: always
    # depends_on:
    # - db
    # - redis
    volumes:
    - .:/app
    ports:
    - 3000:3000
    environment:
    - MY_HOST=${HOSTNAME}
    - MEMCACHED_SERVER=${MEMCACHED_SERVER} #pass from host to container
