version: '3'
services:
  db:
    image: mysql:5.7
    container_name: my-db-container
    volumes:
    - /tmp/ruby-docker-app/db:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=password

  redis:
    image: redis
    container_name: my-redis-container

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    #image: mhamouda1/ruby-docker-web
    image: 359825880475.dkr.ecr.us-east-1.amazonaws.com/ruby-docker-app:latest
    working_dir: /app
    container_name: my-web-container
    depends_on:
    - db
    - redis
    volumes:
    - .:/app
    ports:
    - 3000:3000
    environment:
    - MY_HOST=${HOSTNAME}
